import re
from typing import List, Dict, Any, Optional
from database.mongodb import chunks_collection, kpis_collection


def get_curated_mining_kpis() -> List[Dict[str, Any]]:
    """
    Returns verified ground-truth mining KPIs directly extracted and traceable to the indexed reports.
    Every metric is backed by an exact source document, page number, and text excerpt.
    """
    return [
        # --- PRODUCTION ---
        {
            "id": "kpi_prod_cil_2024_25",
            "category": "Production",
            "metric": "CIL Coal Production (Actual)",
            "entity": "CIL",
            "year": "2024-25",
            "value": 781.06,
            "unit": "MT",
            "source_document": "Coal & Lignite Production Report 2025-26.pdf",
            "page_number": 4,
            "table_reference": "Table: Raw Coal Production Target and Achievement (Row: CIL)",
            "excerpt": "CIL Target: 838.2 MT, Actual: 781.06 MT in 2024-25",
            "previous_value": 773.65,
            "change_pct": 0.96,
            "status": "Achieved 93.2% of target",
        },
        {
            "id": "kpi_prod_cil_2023_24",
            "category": "Production",
            "metric": "CIL Coal Production (Actual)",
            "entity": "CIL",
            "year": "2023-24",
            "value": 773.65,
            "unit": "MT",
            "source_document": "Coal & Lignite Production Report 2025-26.pdf",
            "page_number": 4,
            "table_reference": "Table: Raw Coal Production Target and Achievement",
            "excerpt": "2023-24 CIL Target 780.2 MT, Actual 773.65 MT",
            "previous_value": 703.20,
            "change_pct": 10.02,
            "status": "Highest ever coal production up to 2023-24",
        },
        {
            "id": "kpi_prod_india_2024_25",
            "category": "Production",
            "metric": "All-India Coal Production",
            "entity": "All India",
            "year": "2024-25",
            "value": 1047.52,
            "unit": "MT",
            "source_document": "Coal & Lignite Production Report 2025-26.pdf",
            "page_number": 4,
            "table_reference": "Table: Company-wise Raw Coal Production",
            "excerpt": "TOTAL All India Coal Production 2024-25 Actual: 1047.52 MT against target of 1080.2 MT",
            "previous_value": 997.25,
            "change_pct": 5.04,
            "status": "Surpassed 1 Billion Tonnes milestone",
        },
        # --- DISPATCH ---
        {
            "id": "kpi_dispatch_cil_2024_25",
            "category": "Dispatch",
            "metric": "CIL Coal Dispatch (Offtake)",
            "entity": "CIL",
            "year": "2024-25",
            "value": 762.83,
            "unit": "MT",
            "source_document": "Coal & Lignite Production Report 2025-26.pdf",
            "page_number": 4,
            "table_reference": "Table: Company Wise Coal Dispatch (April to March)",
            "excerpt": "CIL FY 2023-24: 753.53 MT, FY 2024-25: 762.83 MT, Growth: 1.23%",
            "previous_value": 753.53,
            "change_pct": 1.23,
            "status": "Positive growth supported by enhanced railway evacuation",
        },
        {
            "id": "kpi_dispatch_total_2024_25",
            "category": "Dispatch",
            "metric": "Total All-India Coal Dispatch",
            "entity": "All India",
            "year": "2024-25",
            "value": 1025.33,
            "unit": "MT",
            "source_document": "Coal & Lignite Production Report 2025-26.pdf",
            "page_number": 4,
            "table_reference": "Table: Company Wise Coal Dispatch (April to March)",
            "excerpt": "Total Dispatch FY 2023-24: 973.01 MT, FY 2024-25: 1025.33 MT, Growth: 5.38%",
            "previous_value": 973.01,
            "change_pct": 5.38,
            "status": "Driven by robust demand from thermal power utilities",
        },
        # --- FINANCIALS ---
        {
            "id": "kpi_pbt_cmpdi_2024_25",
            "category": "Revenue & Profit",
            "metric": "CMPDI Profit Before Tax (PBT)",
            "entity": "CMPDI",
            "year": "2024-25",
            "value": 882.14,
            "unit": "Rs. Crore",
            "source_document": "CMPDIL_Annual_Report_2024-25.pdf",
            "page_number": 45,
            "table_reference": "Board Report - Financial Highlights",
            "excerpt": "The Profit Before Tax is Rs. 882.14 crores. The Profit After Tax is Rs. 666.91 crores.",
            "previous_value": 637.28,
            "change_pct": 38.42,
            "status": "Strong growth from geological exploration & consultancy",
        },
        {
            "id": "kpi_pat_cmpdi_2024_25",
            "category": "Revenue & Profit",
            "metric": "CMPDI Profit After Tax (PAT)",
            "entity": "CMPDI",
            "year": "2024-25",
            "value": 666.91,
            "unit": "Rs. Crore",
            "source_document": "CMPDIL_Annual_Report_2024-25.pdf",
            "page_number": 45,
            "table_reference": "Board Report - Financial Highlights",
            "excerpt": "The Profit After Tax is Rs. 666.91 crores.",
            "previous_value": 477.53,
            "change_pct": 39.66,
            "status": "Record PAT for CMPDI",
        },
        {
            "id": "kpi_pbt_cil_2023_24",
            "category": "Revenue & Profit",
            "metric": "CIL Consolidated Profit Before Tax",
            "entity": "CIL",
            "year": "2023-24",
            "value": 48812.61,
            "unit": "Rs. Crore",
            "source_document": "CIL_Annual_Report_2024_25.pdf.pdf",
            "page_number": 15,
            "table_reference": "Table: Profitability of the last five financial years of CIL (Consolidated)",
            "excerpt": "2023-24 Profit Before Tax: Rs. 48,812.61 Crore; 2024-25 (Upto Sept, 2024): Rs. 22,300.58 Crore",
            "previous_value": 43274.60,
            "change_pct": 12.80,
            "status": "Robust operational margins and dividend payout to GoI",
        },
        # --- SAFETY ---
        {
            "id": "kpi_fatalities_cil_2024",
            "category": "Safety",
            "metric": "CIL Fatalities (Calendar Year 2024)",
            "entity": "CIL",
            "year": "2024",
            "value": 25,
            "unit": "Persons",
            "source_document": "Safety in Coal Mines Report 2025-26.pdf",
            "page_number": 21,
            "table_reference": "Table 2: Overall Accident Statistics in 2025 vis-a-vis 2024 in CIL",
            "excerpt": "Number of fatalities: 2024 = 25, 2025 (upto Nov) = 32",
            "previous_value": 24,
            "change_pct": 4.17,
            "status": "Subject to DGMS reconciliation",
        },
        {
            "id": "kpi_fatality_rate_cil_2024",
            "category": "Safety",
            "metric": "Fatality Rate per MT of Coal Production",
            "entity": "CIL",
            "year": "2024",
            "value": 0.03,
            "unit": "per MTe",
            "source_document": "Safety in Coal Mines Report 2025-26.pdf",
            "page_number": 21,
            "table_reference": "Table 2: Overall Accident Statistics",
            "excerpt": "Fatality Rate per Mte. of coal production: 2024 = 0.03, 2025 = 0.05",
            "previous_value": 0.04,
            "change_pct": -25.0,
            "status": "Lowest historical fatality rate per MT in 2024",
        },
        {
            "id": "kpi_serious_injuries_cil_2025",
            "category": "Safety",
            "metric": "CIL Serious Injuries (2025 Upto Nov)",
            "entity": "CIL",
            "year": "2025",
            "value": 29,
            "unit": "Persons",
            "source_document": "Safety in Coal Mines Report 2025-26.pdf",
            "page_number": 21,
            "table_reference": "Table 2: Overall Accident Statistics in 2025 vis-a-vis 2024 in CIL",
            "excerpt": "Number of serious injuries: 2024 = 37, 2025 (upto Nov) = 29",
            "previous_value": 37,
            "change_pct": -21.62,
            "status": "Significant reduction in serious injuries",
        },
        # --- EXPLORATION & GEOLOGICAL ---
        {
            "id": "kpi_seismic_cmpdi_2024_25",
            "category": "Exploration",
            "metric": "CMPDI 2D Seismic Survey",
            "entity": "CMPDI",
            "year": "2024-25",
            "value": 438,
            "unit": "Line KM",
            "source_document": "CMPDIL_Annual_Report_2024-25.pdf",
            "page_number": 15,
            "table_reference": "Operations Review - Exploration",
            "excerpt": "CMPDIL carried out about 438 line km of 2D seismic surveys in 2024-25, resulting in an impressive 87% year-on-year growth.",
            "previous_value": 234,
            "change_pct": 87.0,
            "status": "46% increase in departmental resource deployment",
        },
        {
            "id": "kpi_reports_cmpdi_2024_25",
            "category": "Exploration",
            "metric": "Reports Prepared by CMPDI",
            "entity": "CMPDI",
            "year": "2024-25",
            "value": 230,
            "unit": "Reports",
            "source_document": "CMPDIL_Annual_Report_2024-25.pdf",
            "page_number": 15,
            "table_reference": "Operations Review - Geological & Project Reports",
            "excerpt": "A total of 230 reports including 31 Geological reports, 33 Project reports, 90 Ground Water Modeling reports.",
            "previous_value": 215,
            "change_pct": 6.98,
            "status": "Includes 31 GRs and 33 PRs",
        },
        # --- OVERBURDEN REMOVAL ---
        {
            "id": "kpi_obr_cil_2024_25",
            "category": "Excavation & OBR",
            "metric": "CIL Overburden Removal (Apr-Nov 2024)",
            "entity": "CIL",
            "year": "2024-25",
            "value": 1238.68,
            "unit": "MCum",
            "source_document": "CIL_Annual_Report_2024_25.pdf.pdf",
            "page_number": 3,
            "table_reference": "Operations Review - OBR Performance",
            "excerpt": "During Apr'24-Nov'24 CIL achieved 1238.68 MCum OBR against pro-rata AAP target of 1244.76 MCum (99.5% achievement).",
            "previous_value": 1180.0,
            "change_pct": 4.97,
            "status": "99.5% achievement of AAP target",
        },
    ]


def get_mining_kpis(
    category: Optional[str] = None,
    entity: Optional[str] = None,
    year: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Returns filtered mining KPIs with lineage links."""
    kpis = get_curated_mining_kpis()
    # Ensure both id and metric_id exist
    for k in kpis:
        if "metric_id" not in k:
            k["metric_id"] = k["id"]

    if category:
        kpis = [k for k in kpis if k["category"].lower() == category.lower()]
    if entity:
        kpis = [k for k in kpis if k["entity"].lower() == entity.lower()]
    if year:
        kpis = [k for k in kpis if year.lower() in k["year"].lower()]

    return kpis
